import { ArrayFn1 } from "./array/ex1";
import { ArrayFn11 } from "./array/ex11";
import { ArrayFn12 } from "./array/ex12";
import { ArrayFn13 } from "./array/ex13";
import { ArrayFn14 } from "./array/ex14";
import { ArrayFn2 } from "./array/ex2";
import { ArrayFn3 } from "./array/ex3";
import { ArrayFn30 } from "./array/ex30";
import { ArrayFn4 } from "./array/ex4";
import { ArrayFn5 } from "./array/ex5";
import { ArrayFn6 } from "./array/ex6";
import { ArrayFn7 } from "./array/ex7";
import { CounterIncludes } from "./closure/ex1";
import { MultiplierIncludes } from "./closure/ex2";
import { OperationIncludes } from "./closure/ex3";
import { MemoizeExample } from "./closure/ex4";
import { DictFn1 } from "./dict/ex1";
import { DictFn10 } from "./dict/ex10";
import { DictFn3 } from "./dict/ex3";
import { DictFn4 } from "./dict/ex4";
import { DictFn6 } from "./dict/ex6";
import { DictFn7 } from "./dict/ex7";
import { DictFn8 } from "./dict/ex8";
import { FunctionFn1 } from "./function/ex1";
import { FunctionFn2 } from "./function/ex2";
import { FunctionThrottleExample } from "./function/ex3";
import { optionFn1 } from "./option/ex1";
import { optionFn2 } from "./option/ex2";

ArrayFn1();
ArrayFn2();
ArrayFn3();
ArrayFn4();
ArrayFn5();
ArrayFn6();
ArrayFn7();
ArrayFn11();
ArrayFn12();
ArrayFn13();
ArrayFn14();
ArrayFn30();
CounterIncludes();
MultiplierIncludes();
OperationIncludes();
MemoizeExample();
DictFn1();
DictFn3();
DictFn4();
DictFn6();
DictFn7();
DictFn8();
DictFn10();
FunctionFn1();
FunctionFn2();
FunctionThrottleExample();
optionFn2();

optionFn1();
